# Automated setup and configuration for my personal linux machines
# https://github.com/rainyskye/penguin

- name: Prepare Programs and Utilities
  hosts: localhost
  become: true
  tasks:
  - name: Remove preinstalled Fedora packages
    ansible.builtin.dnf:
      name:
        - totem # gnome videos
        - gnome-maps
        - gnome-calendar
        - gnome-contacts
        - gnome-clocks
        - cheese
        - cheese-libs
        - rhythmbox
        - gnome-tour
        - gnome-photos
        - gnome-weather
        - yelp # help app
        - yelp-libs # help app libraries?
        - libreoffice-calc
        - libreoffice-core
        - libreoffice-data
        - libreoffice-emailmerge
        - libreoffice-filters
        - libreoffice-graphicfilter
        - libreoffice-gtk3
        - libreoffice-gtk4
        - libreoffice-help-en
        - libreoffice-impress
        - libreoffice-langpack-en
        - libreoffice-ogltrans
        - libreoffice-opensymbol-fonts
        - libreoffice-pdfimport
        - libreoffice-pyuno
        - libreoffice-writer
        - libreoffice-xsltfilter
      state: absent
  - name: Import 1Password RPM Key
    ansible.builtin.rpm_key:
      state: present
      key: https://downloads.1password.com/linux/keys/1password.asc
  - name: TEMP - Add 1Password Repo
    ansible.builtin.command: sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
  - name: Install packages using dnf
    ansible.builtin.dnf:
      name: 
        - neofetch
        - 1password
      state: latest
###
#  - name: Create .ssh folder in home directory
#    ansible.builtin.file:
#      path: /home/skye/.ssh
#      state: directory
###
#  TODO: Add 1Password SSH Agent setup
###
#  - name: Add the Flathub remote repo to Flatpak # Not working?
#    community.general.flatpak_remote: # Disabled because didn't work
#      name: flathub
#      state: present
#      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  - name: Add Flathub Remote Repo # TODO: do this properly lol
    ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - name: Install multiple packages
    community.general.flatpak:
      name:
        - com.spotify.Client # Spotify
        - org.gabmus.hydrapaper # HydraPaper (Multi-Monitor Wallpaper Tool)
        - com.discordapp.Discord # Discord
        - com.github.tchx84.Flatseal # Flatseal (Flatpak Manager)
        - org.qbittorrent.qBittorrent # qBittorrent
        - org.signal.Signal # Signal Desktop
        - org.telegram.desktop # Telegram Desktop
        - io.mpv.Mpv # mpv (Video/Audio Player)
        # - com.visualstudio.code # Visual Studio Code (Disabled due to some limitations with flatpak version)
        - com.rafaelmardojai.Blanket # Blanket (Noise Generator)
        - org.prismlauncher.PrismLauncher # Prism Launcher (Minecraft)
  - name: Import VSCode RPM Key
    ansible.builtin.rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc
  - name: TEMP - Setup VSCode Repo
    ansible.builtin.command: sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
  - name: Install VSCode
    ansible.builtin.dnf:
      name: code
      state: latest


- name: Setup and configure Syncthing
  hosts: localhost
  vars_files:
    - ../config.yml
#  user: skye # needs to be a separate play due to user switching
  tasks:
  - name: Install syncthing
    become: true
    ansible.builtin.dnf:
      name: syncthing
  - name: Enable the syncthing service to start on boot
    ansible.builtin.systemd:
      name: syncthing.service
      enabled: true
      state: started
      scope: user
      masked: false
#    become_user: {user}

- name: Setup Git
  hosts: localhost
  vars_files:
    - ../config.yml
  tasks:
    - name: Set nano to default editor
      community.general.git_config:
        name: core.editor
        scope: global
        value: nano
    - name: Set User Name
      community.general.git_config:
        name: user.name
        scope: global
        value: {user.name}
    - name: Set User Email
      community.general.git_config:
        name: user.email
        scope: global
        value: {user.email}

- name: Configure Gnome Extensions
  hosts: localhost
  become: true
  tasks:
  - name: Install dash-to-dock extension
    ansible.builtin.dnf:
      name:
        - gnome-shell-extension-dash-to-dock
      state: latest
  - name: Install Gnome Tweaks and Gnome Extensions
    ansible.builtin.dnf:
      name:
        - gnome-extensions-app
        - gnome-tweaks
  - name: Next Steps Messages
    ansible.builtin.debug:
      msg: "A reboot (or relogin) is required to be able to enable the Dash-to-Dock extension."
